package com.aimtech.arrowcore.core.enums;

public enum RoleEnum {
    USER_READ("ROLE_USER_READ"),
    USER_CRETE("ROLE_USER_CREATE"),
    USER_UPDATE("ROLE_USER_UPDATE"),
    USER_CHANGE_STATUS("ROLE_USER_CHANGE_STATUS"),
    COMPANY_READ("ROLE_COMPANY_READ"),
    COMPANY_CREATE("ROLE_COMPANY_CREATE"),
    COMPANY_UPDATE("ROLE_COMPANY_UPDATE"),
    COMPANY_CHANGE_STATUS("ROLE_COMPANY_CHANGE_STATUS"),
    COMPANY_CHANGE_REPRESENTATIVES("ROLE_COMPANY_CHANGE_REPRESENTATIVES"),
    COMPANY_ASSOCIATE_AS_BRANCH("ROLE_COMPANY_ASSOCIATE_AS_BRANCH"),
    COUNTRY_READ("ROLE_COUNTRY_READ"),
    COUNTRY_CREATE("ROLE_COUNTRY_CREATE"),
    COUNTRY_UPDATE("ROLE_COUNTRY_UPDATE"),
    COUNTRY_CHANGE_STATUS("ROLE_COUNTRY_CHANGE_STATUS"),
    STATE_READ("ROLE_STATE_READ"),
    STATE_CREATE("ROLE_STATE_CREATE"),
    STATE_UPDATE("ROLE_STATE_UPDATE"),
    STATE_CHANGE_STATUS("ROLE_STATE_CHANGE_STATUS"),
    CITY_READ("ROLE_CITY_READ"),
    CITY_CREATE("ROLE_CITY_CREATE"),
    CITY_UPDATE("ROLE_CITY_UPDATE"),
    CITY_CHANGE_STATUS("ROLE_CITY_CHANGE_STATUS"),
    STREET_TYPE_READ("ROLE_STREET_TYPE_READ"),
    STREET_TYPE_CREATE("ROLE_STREET_TYPE_CREATE"),
    STREET_TYPE_UPDATE("ROLE_STREET_TYPE_UPDATE"),
    STREET_TYPE_CHANGE_STATUS("ROLE_STREET_TYPE_CHANGE_STATUS");

    private final String roleName;

    RoleEnum(String roleName) {
        this.roleName = roleName;
    }

    public String getRoleName() {
        return roleName;
    }
}
