spring:
  application:
    name: ArrowCore
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:arrow}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASS:1234567}
    driver-class-name: org.postgresql.Driver
    hikari:
      max-lifetime: 1800000
      idle-timeout: 60000
      connection-test-query: SELECT 1
      maximum-pool-size: 10
      minimum-idle: 5

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        ddl-auto: none
  flyway:
    enabled: true
    schemas: public
    locations: classpath:db/migration
    placeholders:
      schema: public
arrowcore:
  app:
    default-values:
      default-schema-name: public
      admin-profile-name: Administrador
      admin-profile-description: Perfil de administrador do sistema gerado automáticamente
      admin-first-name: Admin
      admin-last-name: AIM Tech
      admin-username: admin@aimtech.com.br
      admin-password: Mudar@123
      minimum-password-length: 8
      recovery-token:
        expiry-in-seconds: ${PASSWORD_RECOVER_EXPIRATION_TOKEN_SECONDS:1800}
        redirect-uri: ${PASSWORD_RECOVER_REDIRECT_URI:http://localhost:5173/recover-password}
      login-attempts:
        max-attempts: 5
        lockout-duration-in-seconds: 900
    kafka:
      server: localhost:9092
      retries: 10
      request-timeout: 15000
      retention-ms: "604800000"
      cleanup-policy: "delete"
      topics:
        create-user: "create-user-topic"
  security:
    key:
      private-key: classpath:keys/app.key
      public-key: classpath:keys/app.pub
    token:
      expiry-in-seconds: 3600
      issuer: arrow-core-microservice
      audience: arrow-system
  system:
    parameters:
      - key: "system.theme"
        value: "light"
        type: "STRING"
      - key: "system.email.notifications"
        value: "true"
        type: "BOOLEAN"
      - key: "system.max.users"
        value: "100"
        type: "NUMBER"
      - key: "admin.user.use_internal_domain"
        value: "true"
        type: "BOOLEAN"