CREATE SEQUENCE IF NOT EXISTS tb_revision_entity_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE tb_business_group
(
    internal_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    external_id   UUID                                    NOT NULL,
    public_name   VARCHAR(255)                            NOT NULL,
    tenant_domain VARCHAR(255)                            NOT NULL,
    schema_name   VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_tb_business_group PRIMARY KEY (internal_id)
);

CREATE TABLE tb_city
(
    internal_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    city_name   VARCHAR(100)                            NOT NULL,
    city_code   VARCHAR(20)                             NOT NULL,
    latitude    DECIMAL(9, 6),
    longitude   DECIMAL(9, 6),
    is_active   BOOLEAN DEFAULT TRUE                    NOT NULL,
    state_id    BIGINT                                  NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_tb_city PRIMARY KEY (internal_id)
);

CREATE TABLE tb_company
(
    internal_id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    external_id            UUID                                    NOT NULL,
    trade_name             VARCHAR(255)                            NOT NULL,
    corporate_name         VARCHAR(255)                            NOT NULL,
    cnpj                   VARCHAR(14)                             NOT NULL,
    state_registration     VARCHAR(20)                             NOT NULL,
    municipal_registration VARCHAR(20)                             NOT NULL,
    foundation_date        date                                    NOT NULL,
    tax_regime_id          BIGINT                                  NOT NULL,
    email                  VARCHAR(255)                            NOT NULL,
    phone                  VARCHAR(15)                             NOT NULL,
    street_type_id         BIGINT,
    street_name            VARCHAR(255)                            NOT NULL,
    street_number          VARCHAR(20)                             NOT NULL,
    neighborhood           VARCHAR(100),
    complement             VARCHAR(100),
    zip_code               VARCHAR(8)                              NOT NULL,
    city_id                BIGINT,
    logo_url               VARCHAR(255),
    is_active              BOOLEAN DEFAULT TRUE                    NOT NULL,
    parent_company_id      BIGINT,
    business_group         BIGINT,
    created_at             TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at             TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_tb_company PRIMARY KEY (internal_id)
);

CREATE TABLE tb_company_representative
(
    internal_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cpf          VARCHAR(11)                             NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    phone_fixed  VARCHAR(15),
    phone_mobile VARCHAR(15)                             NOT NULL,
    email        VARCHAR(255),
    position     VARCHAR(100),
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_tb_company_representative PRIMARY KEY (internal_id)
);

CREATE TABLE tb_company_representative_association
(
    company_id        BIGINT NOT NULL,
    representative_id BIGINT NOT NULL,
    CONSTRAINT pk_tb_company_representative_association PRIMARY KEY (company_id, representative_id)
);

CREATE TABLE tb_country
(
    internal_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    country_name VARCHAR(100)                            NOT NULL,
    iso_code     VARCHAR(3)                              NOT NULL,
    CONSTRAINT pk_tb_country PRIMARY KEY (internal_id)
);

CREATE TABLE tb_log_city
(
    rev         INTEGER NOT NULL,
    revtype     SMALLINT,
    internal_id BIGINT  NOT NULL,
    city_name   VARCHAR(100),
    city_code   VARCHAR(20),
    latitude    DECIMAL,
    longitude   DECIMAL,
    is_active   BOOLEAN DEFAULT TRUE,
    state_id    BIGINT,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_tb_log_city PRIMARY KEY (rev, internal_id)
);

CREATE TABLE tb_log_company
(
    rev                    INTEGER NOT NULL,
    revtype                SMALLINT,
    internal_id            BIGINT  NOT NULL,
    external_id            UUID,
    trade_name             VARCHAR(255),
    corporate_name         VARCHAR(255),
    cnpj                   VARCHAR(14),
    state_registration     VARCHAR(20),
    municipal_registration VARCHAR(20),
    foundation_date        TIMESTAMP WITHOUT TIME ZONE,
    tax_regime_id          BIGINT,
    email                  VARCHAR(255),
    phone                  VARCHAR(15),
    street_type_id         BIGINT,
    street_name            VARCHAR(255),
    street_number          VARCHAR(20),
    neighborhood           VARCHAR(100),
    complement             VARCHAR(100),
    zip_code               VARCHAR(8),
    city_id                BIGINT,
    logo_url               VARCHAR(255),
    is_active              BOOLEAN DEFAULT TRUE,
    parent_company_id      BIGINT,
    business_group         BIGINT,
    created_at             TIMESTAMP WITHOUT TIME ZONE,
    updated_at             TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_tb_log_company PRIMARY KEY (rev, internal_id)
);

CREATE TABLE tb_log_company_representative
(
    rev          INTEGER NOT NULL,
    revtype      SMALLINT,
    internal_id  BIGINT  NOT NULL,
    cpf          VARCHAR(11),
    name         VARCHAR(255),
    phone_fixed  VARCHAR(15),
    phone_mobile VARCHAR(15),
    email        VARCHAR(255),
    position     VARCHAR(100),
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_tb_log_company_representative PRIMARY KEY (rev, internal_id)
);

CREATE TABLE tb_log_company_representative_association
(
    company_id        BIGINT  NOT NULL,
    representative_id BIGINT  NOT NULL,
    rev               INTEGER NOT NULL,
    revtype           SMALLINT,
    CONSTRAINT pk_tb_log_company_representative_association PRIMARY KEY (company_id, representative_id, rev)
);

CREATE TABLE tb_log_profile
(
    rev          INTEGER NOT NULL,
    revtype      SMALLINT,
    internal_id  BIGINT  NOT NULL,
    external_id  UUID,
    profile_name VARCHAR(255),
    description  VARCHAR(255),
    is_active    BOOLEAN,
    CONSTRAINT pk_tb_log_profile PRIMARY KEY (rev, internal_id)
);

CREATE TABLE tb_log_user
(
    rev            INTEGER NOT NULL,
    revtype        SMALLINT,
    internal_id    BIGINT  NOT NULL,
    external_id    UUID,
    first_name     VARCHAR(255),
    last_name      VARCHAR(255),
    username       VARCHAR(255),
    password       VARCHAR(255),
    last_login     TIMESTAMP WITHOUT TIME ZONE,
    is_active      BOOLEAN,
    is_first_login BOOLEAN DEFAULT TRUE,
    business_group BIGINT,
    CONSTRAINT pk_tb_log_user PRIMARY KEY (rev, internal_id)
);

CREATE TABLE tb_log_user_profile
(
    profile_id BIGINT  NOT NULL,
    rev        INTEGER NOT NULL,
    revtype    SMALLINT,
    user_id    BIGINT  NOT NULL,
    CONSTRAINT pk_tb_log_user_profile PRIMARY KEY (profile_id, rev, user_id)
);

CREATE TABLE tb_password_recover
(
    internal_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token       VARCHAR(255)                            NOT NULL,
    username    VARCHAR(255)                            NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE                NOT NULL,
    expiration  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    used_at     TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_tb_password_recover PRIMARY KEY (internal_id)
);

CREATE TABLE tb_profile
(
    internal_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    external_id  UUID                                    NOT NULL,
    profile_name VARCHAR(255)                            NOT NULL,
    description  VARCHAR(255),
    is_active    BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_tb_profile PRIMARY KEY (internal_id)
);

CREATE TABLE tb_profile_role
(
    profile_id BIGINT NOT NULL,
    role_id    BIGINT NOT NULL,
    CONSTRAINT pk_tb_profile_role PRIMARY KEY (profile_id, role_id)
);

CREATE TABLE tb_profile_role_aud
(
    profile_id BIGINT  NOT NULL,
    rev        INTEGER NOT NULL,
    revtype    SMALLINT,
    role_id    BIGINT  NOT NULL,
    CONSTRAINT pk_tb_profile_role_aud PRIMARY KEY (profile_id, rev, role_id)
);

CREATE TABLE tb_revision_entity
(
    id         INTEGER NOT NULL,
    timestamp  BIGINT  NOT NULL,
    username   VARCHAR(255),
    ip_address VARCHAR(255),
    CONSTRAINT pk_tb_revision_entity PRIMARY KEY (id)
);

CREATE TABLE tb_role
(
    internal_id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    authority                  VARCHAR(255)                            NOT NULL,
    role_interface_name        VARCHAR(255),
    role_interface_description VARCHAR(255),
    CONSTRAINT pk_tb_role PRIMARY KEY (internal_id)
);

CREATE TABLE tb_state
(
    internal_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    state_name  VARCHAR(100)                            NOT NULL,
    state_code  VARCHAR(2)                              NOT NULL,
    country_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_tb_state PRIMARY KEY (internal_id)
);

CREATE TABLE tb_street_type
(
    internal_id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    street_type_name         VARCHAR(50)                             NOT NULL,
    street_type_abbreviation VARCHAR(10)                             NOT NULL,
    CONSTRAINT pk_tb_street_type PRIMARY KEY (internal_id)
);

CREATE TABLE tb_tax_regime
(
    internal_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tax_regime_name VARCHAR(255)                            NOT NULL,
    is_active       BOOLEAN DEFAULT TRUE                    NOT NULL,
    CONSTRAINT pk_tb_tax_regime PRIMARY KEY (internal_id)
);

CREATE TABLE tb_user
(
    internal_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    external_id    UUID                                    NOT NULL,
    first_name     VARCHAR(255)                            NOT NULL,
    last_name      VARCHAR(255)                            NOT NULL,
    username       VARCHAR(255)                            NOT NULL,
    password       VARCHAR(255)                            NOT NULL,
    last_login     TIMESTAMP WITHOUT TIME ZONE,
    is_active      BOOLEAN                                 NOT NULL,
    is_first_login BOOLEAN DEFAULT TRUE                    NOT NULL,
    business_group BIGINT,
    CONSTRAINT pk_tb_user PRIMARY KEY (internal_id)
);

CREATE TABLE tb_user_profile
(
    profile_id BIGINT NOT NULL,
    user_id    BIGINT NOT NULL,
    CONSTRAINT pk_tb_user_profile PRIMARY KEY (profile_id, user_id)
);

ALTER TABLE tb_business_group
    ADD CONSTRAINT uc_tb_business_group_external UNIQUE (external_id);

ALTER TABLE tb_business_group
    ADD CONSTRAINT uc_tb_business_group_schema_name UNIQUE (schema_name);

ALTER TABLE tb_company
    ADD CONSTRAINT uc_tb_company_cnpj UNIQUE (cnpj);

ALTER TABLE tb_company
    ADD CONSTRAINT uc_tb_company_external UNIQUE (external_id);

ALTER TABLE tb_company_representative
    ADD CONSTRAINT uc_tb_company_representative_cpf UNIQUE (cpf);

ALTER TABLE tb_profile
    ADD CONSTRAINT uc_tb_profile_external UNIQUE (external_id);

ALTER TABLE tb_profile
    ADD CONSTRAINT uc_tb_profile_profile_name UNIQUE (profile_name);

ALTER TABLE tb_role
    ADD CONSTRAINT uc_tb_role_authority UNIQUE (authority);

ALTER TABLE tb_user
    ADD CONSTRAINT uc_tb_user_external UNIQUE (external_id);

ALTER TABLE tb_user
    ADD CONSTRAINT uc_tb_user_username UNIQUE (username);

ALTER TABLE tb_city
    ADD CONSTRAINT FK_TB_CITY_ON_STATE FOREIGN KEY (state_id) REFERENCES tb_state (internal_id);

ALTER TABLE tb_company
    ADD CONSTRAINT FK_TB_COMPANY_ON_BUSINESS_GROUP FOREIGN KEY (business_group) REFERENCES tb_business_group (internal_id);

ALTER TABLE tb_company
    ADD CONSTRAINT FK_TB_COMPANY_ON_CITY FOREIGN KEY (city_id) REFERENCES tb_city (internal_id);

ALTER TABLE tb_company
    ADD CONSTRAINT FK_TB_COMPANY_ON_PARENT_COMPANY FOREIGN KEY (parent_company_id) REFERENCES tb_company (internal_id);

ALTER TABLE tb_company
    ADD CONSTRAINT FK_TB_COMPANY_ON_STREET_TYPE FOREIGN KEY (street_type_id) REFERENCES tb_street_type (internal_id);

ALTER TABLE tb_company
    ADD CONSTRAINT FK_TB_COMPANY_ON_TAX_REGIME FOREIGN KEY (tax_regime_id) REFERENCES tb_tax_regime (internal_id);

ALTER TABLE tb_log_city
    ADD CONSTRAINT FK_TB_LOG_CITY_ON_REV FOREIGN KEY (rev) REFERENCES tb_revision_entity (id);

ALTER TABLE tb_log_company
    ADD CONSTRAINT FK_TB_LOG_COMPANY_ON_REV FOREIGN KEY (rev) REFERENCES tb_revision_entity (id);

ALTER TABLE tb_log_company_representative
    ADD CONSTRAINT FK_TB_LOG_COMPANY_REPRESENTATIVE_ON_REV FOREIGN KEY (rev) REFERENCES tb_revision_entity (id);

ALTER TABLE tb_log_profile
    ADD CONSTRAINT FK_TB_LOG_PROFILE_ON_REV FOREIGN KEY (rev) REFERENCES tb_revision_entity (id);

ALTER TABLE tb_log_user
    ADD CONSTRAINT FK_TB_LOG_USER_ON_REV FOREIGN KEY (rev) REFERENCES tb_revision_entity (id);

ALTER TABLE tb_state
    ADD CONSTRAINT FK_TB_STATE_ON_COUNTRY FOREIGN KEY (country_id) REFERENCES tb_country (internal_id);

ALTER TABLE tb_user
    ADD CONSTRAINT FK_TB_USER_ON_BUSINESS_GROUP FOREIGN KEY (business_group) REFERENCES tb_business_group (internal_id);

ALTER TABLE tb_log_company_representative_association
    ADD CONSTRAINT fk_tb_log_company_representative_association_on_rev FOREIGN KEY (rev) REFERENCES tb_revision_entity (id);

ALTER TABLE tb_log_user_profile
    ADD CONSTRAINT fk_tb_log_user_profile_on_rev FOREIGN KEY (rev) REFERENCES tb_revision_entity (id);

ALTER TABLE tb_profile_role_aud
    ADD CONSTRAINT fk_tb_profile_role_aud_on_rev FOREIGN KEY (rev) REFERENCES tb_revision_entity (id);

ALTER TABLE tb_company_representative_association
    ADD CONSTRAINT fk_tb_company_representations_ass_on_company FOREIGN KEY (company_id) REFERENCES tb_company (internal_id);

ALTER TABLE tb_company_representative_association
    ADD CONSTRAINT fk_tb_company_representations_ass_on_company_representative FOREIGN KEY (representative_id) REFERENCES tb_company_representative (internal_id);

ALTER TABLE tb_profile_role
    ADD CONSTRAINT fk_tb_profile_role_on_profile FOREIGN KEY (profile_id) REFERENCES tb_profile (internal_id);

ALTER TABLE tb_profile_role
    ADD CONSTRAINT fk_tb_profile_role_on_role FOREIGN KEY (role_id) REFERENCES tb_role (internal_id);

ALTER TABLE tb_user_profile
    ADD CONSTRAINT fk_tb_user_profile_on_profile FOREIGN KEY (profile_id) REFERENCES tb_profile (internal_id);

ALTER TABLE tb_user_profile
    ADD CONSTRAINT fk_tb_user_profile_on_user FOREIGN KEY (user_id) REFERENCES tb_user (internal_id);