CREATE TABLE tb_city
(
    internal_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    city_name   VARCHAR(100)                            NOT NULL,
    city_code   VARCHAR(20)                             NOT NULL,
    latitude    DECIMAL(9, 6),
    longitude   DECIMAL(9, 6),
    is_active   BOOLEAN DEFAULT TRUE                    NOT NULL,
    state_id    BIGINT                                  NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_tb_city PRIMARY KEY (internal_id)
);

CREATE TABLE tb_company
(
    internal_id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    external_id            UUID                                    NOT NULL,
    trade_name             VARCHAR(255)                            NOT NULL,
    corporate_name         VARCHAR(255)                            NOT NULL,
    cnpj                   VARCHAR(14)                             NOT NULL,
    state_registration     VARCHAR(20)                             NOT NULL,
    municipal_registration VARCHAR(20)                             NOT NULL,
    foundation_date        time WITHOUT TIME ZONE                  NOT NULL,
    email                  VARCHAR(255)                            NOT NULL,
    phone                  VARCHAR(15)                             NOT NULL,
    street_type_id         BIGINT,
    street_name            VARCHAR(255)                            NOT NULL,
    street_number          VARCHAR(20)                             NOT NULL,
    neighborhood           VARCHAR(100),
    complement             VARCHAR(100),
    zip_code               VARCHAR(8)                              NOT NULL,
    city_id                BIGINT,
    logo_url               VARCHAR(255),
    is_active              BOOLEAN DEFAULT TRUE                    NOT NULL,
    created_at             TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at             TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_tb_company PRIMARY KEY (internal_id)
);

CREATE TABLE tb_company_representative
(
    internal_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    company_id   BIGINT,
    cpf          VARCHAR(11)                             NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    phone_fixed  VARCHAR(15),
    phone_mobile VARCHAR(15)                             NOT NULL,
    email        VARCHAR(255),
    position     VARCHAR(100),
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_tb_company_representative PRIMARY KEY (internal_id)
);

CREATE TABLE tb_company_representative_association
(
    company_id        BIGINT NOT NULL,
    representative_id BIGINT NOT NULL,
    CONSTRAINT pk_tb_company_representative_association PRIMARY KEY (company_id, representative_id)
);

CREATE TABLE tb_country
(
    internal_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    country_name VARCHAR(100)                            NOT NULL,
    iso_code     VARCHAR(3)                              NOT NULL,
    CONSTRAINT pk_tb_country PRIMARY KEY (internal_id)
);

CREATE TABLE tb_state
(
    internal_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    state_name  VARCHAR(100)                            NOT NULL,
    state_code  VARCHAR(2)                              NOT NULL,
    country_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_tb_state PRIMARY KEY (internal_id)
);

CREATE TABLE tb_tax_regime
(
    internal_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tax_regime_name VARCHAR(255)                            NOT NULL,
    is_active       BOOLEAN DEFAULT TRUE                    NOT NULL,
    CONSTRAINT pk_tb_tax_regime PRIMARY KEY (internal_id)
);

ALTER TABLE tb_company
    ADD CONSTRAINT uc_tb_company_cnpj UNIQUE (cnpj);

ALTER TABLE tb_company
    ADD CONSTRAINT uc_tb_company_external UNIQUE (external_id);

ALTER TABLE tb_company_representative
    ADD CONSTRAINT uc_tb_company_representative_cpf UNIQUE (cpf);

ALTER TABLE tb_city
    ADD CONSTRAINT FK_TB_CITY_ON_STATE FOREIGN KEY (state_id) REFERENCES tb_state (internal_id);

ALTER TABLE tb_company
    ADD CONSTRAINT FK_TB_COMPANY_ON_CITY FOREIGN KEY (city_id) REFERENCES tb_city (internal_id);

ALTER TABLE tb_company
    ADD CONSTRAINT FK_TB_COMPANY_ON_STREET_TYPE FOREIGN KEY (street_type_id) REFERENCES tb_city (internal_id);

ALTER TABLE tb_company_representative
    ADD CONSTRAINT FK_TB_COMPANY_REPRESENTATIVE_ON_COMPANY FOREIGN KEY (company_id) REFERENCES tb_company (internal_id);

ALTER TABLE tb_state
    ADD CONSTRAINT FK_TB_STATE_ON_COUNTRY FOREIGN KEY (country_id) REFERENCES tb_country (internal_id);

ALTER TABLE tb_company_representative_association
    ADD CONSTRAINT fk_tb_company_representative_on_company FOREIGN KEY (company_id) REFERENCES tb_company (internal_id);

ALTER TABLE tb_company_representative_association
    ADD CONSTRAINT k_tb_company_representative_on_company_representative FOREIGN KEY (representative_id) REFERENCES tb_company_representative (internal_id);