ALTER TABLE tb_company
    DROP CONSTRAINT fk_tb_company_on_street_type;

CREATE TABLE tb_street_type
(
    internal_id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    street_type_name VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_tb_street_type PRIMARY KEY (internal_id)
);

ALTER TABLE tb_company
    ADD CONSTRAINT FK_TB_COMPANY_ON_STREET_TYPE FOREIGN KEY (street_type_id) REFERENCES tb_street_type (internal_id);