CREATE TABLE tb_business_group
(
    internal_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    external_id   VARCHAR(255)                            NOT NULL,
    public_name   VARCHAR(255)                            NOT NULL,
    tenant_domain VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_tb_business_group PRIMARY KEY (internal_id)
);

CREATE TABLE tb_user
(
    internal_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    external_id    VARCHAR(255)                            NOT NULL,
    first_name     VARCHAR(255)                            NOT NULL,
    last_name      VARCHAR(255)                            NOT NULL,
    username       VARCHAR(255)                            NOT NULL,
    password       VARCHAR(255)                            NOT NULL,
    last_login     TIMESTAMP WITHOUT TIME ZONE,
    business_group BIGINT,
    CONSTRAINT pk_tb_user PRIMARY KEY (internal_id)
);

ALTER TABLE tb_business_group
    ADD CONSTRAINT uc_tb_business_group_external UNIQUE (external_id);

ALTER TABLE tb_user
    ADD CONSTRAINT uc_tb_user_external UNIQUE (external_id);

ALTER TABLE tb_user
    ADD CONSTRAINT uc_tb_user_username UNIQUE (username);

ALTER TABLE tb_user
    ADD CONSTRAINT FK_TB_USER_ON_BUSINESS_GROUP FOREIGN KEY (business_group) REFERENCES tb_business_group (internal_id);