CREATE TABLE tb_log_system_parameters
(
    rev         INTEGER NOT NULL,
    revtype     SMALLINT,
    id          BIGINT  NOT NULL,
    param_key   VARCHAR(255),
    param_value VARCHAR(255),
    param_type  VARCHAR(255),
    CONSTRAINT pk_tb_log_system_parameters PRIMARY KEY (rev, id)
);

CREATE TABLE tb_system_parameters
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    param_key   VARCHAR(255)                            NOT NULL,
    param_value VARCHAR(255),
    param_type  VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_tb_system_parameters PRIMARY KEY (id)
);

ALTER TABLE tb_system_parameters
    ADD CONSTRAINT uc_tb_system_parameters_param_key UNIQUE (param_key);

ALTER TABLE tb_log_system_parameters
    ADD CONSTRAINT FK_TB_LOG_SYSTEM_PARAMETERS_ON_REV FOREIGN KEY (rev) REFERENCES tb_revision_entity (id);

CREATE INDEX idx_param_key ON tb_system_parameters (param_key);