CREATE TABLE tb_profile
(
    internal_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    external_id VARCHAR(255)                            NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    is_active   BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_tb_profile PRIMARY KEY (internal_id)
);

CREATE TABLE tb_profile_role
(
    profile_id BIGINT NOT NULL,
    role_id    BIGINT NOT NULL,
    CONSTRAINT pk_tb_profile_role PRIMARY KEY (profile_id, role_id)
);

CREATE TABLE tb_role
(
    internal_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    authority   VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_tb_role PRIMARY KEY (internal_id)
);

ALTER TABLE tb_user
    ADD is_active BOOLEAN;

ALTER TABLE tb_user
    ADD profile_id BIGINT;

ALTER TABLE tb_user
    ALTER COLUMN is_active SET NOT NULL;

ALTER TABLE tb_profile
    ADD CONSTRAINT uc_tb_profile_external UNIQUE (external_id);

ALTER TABLE tb_role
    ADD CONSTRAINT uc_tb_role_authority UNIQUE (authority);

ALTER TABLE tb_user
    ADD CONSTRAINT uc_tb_user_profile UNIQUE (profile_id);

ALTER TABLE tb_user
    ADD CONSTRAINT FK_TB_USER_ON_PROFILE FOREIGN KEY (profile_id) REFERENCES tb_profile (internal_id);

ALTER TABLE tb_profile_role
    ADD CONSTRAINT fk_tb_profile_role_on_profile FOREIGN KEY (profile_id) REFERENCES tb_profile (internal_id);

ALTER TABLE tb_profile_role
    ADD CONSTRAINT fk_tb_profile_role_on_role FOREIGN KEY (role_id) REFERENCES tb_role (internal_id);