CREATE TABLE tb_password_recover
(
    internal_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token       VARCHAR(255)                            NOT NULL,
    username    VARCHAR(255)                            NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE                NOT NULL,
    expiration  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    used_at     TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_tb_password_recover PRIMARY KEY (internal_id)
);