name: Build ArrowNotifications Application

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build ArrowNotifications
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./ArrowNotifications

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      -
        name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      -
        name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('ArrowNotifications/gradle.lockfile') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      -
        name: Build with Gradle
        run: ./gradlew build -x test

      -
        name: Run tests
        run: ./gradlew test

      -
        name: Generate tag
        id: generate_tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: 'true'
          tags: rafaeljaber/arrow-notifications:latest,rafaeljaber/arrow-notificaitons:${{ steps.generate_tag.outputs.sha }}